packages/ipa-core/src/IpaControls/Table/Cell.jsx
packages/ipa-core/src/IpaControls/Table/Table.jsx
packages/ipa-core/src/IpaPageComponents/entities/EntityView.jsx

Selected entities in the EntityView where being reset when a user selected on an entity in the EntityListView

DBM-2198 Data view is getting reset 

---

packages/ipa-core/src/IpaPageComponents/entities/WithEntityStore.jsx

clear entity button not working

DBM-2213 - fix: clear entity button not working

---

packages/ipa-core/package-lock.json
packages/ipa-core/package.json
packages/ipa-core/src/IpaPageComponents/files/DocumentView.jsx

Fix resolution errors with importing iaf-doc-viewer

Add dtplaform/iaf-doc-viewer dependency and update import

---

packages/ipa-core/src/IpaPageComponents/entities/EntitySelectionPanel.jsx
packages/ipa-core/src/IpaPageComponents/entities/EntityView.jsx
packages/ipa-core/src/IpaPageComponents/entities/WithEntitySearch.jsx
packages/ipa-core/src/IpaPageComponents/entities/WithEntityStore.jsx
packages/ipa-core/src/redux/main.js
packages/ipa-core/src/redux/slices/entities-higher-order-reducer.js
packages/ipa-core/src/redux/slices/entities.js

Added in a new redux state slice to have better control over the selected entities in the Navigator search panels.

DBM-2261: Resolves entity search panel issues

---

packages/ipa-core/src/IpaControls/ReactiveTreeControl.jsx

Apply same fix already made to v2.3 - https://github.com/Invicara/InvicaraPlatformApplication/pull/182
https://invicara.atlassian.net/browse/DBM-2260
Fixes:
* "Something went wrong" error when attempting to expand a parent node on the tree
* UI issue after expanding parent node, the height is not expanded and the children node appear in the background
* Loading spinner added when expanding tree branch because it is async operation that makes api call

DBM-2260: Fix crash when expanding tree search & children nodes UI issue

---

packages/ipa-core/src/IpaControls/ControlProvider.jsx

https://invicara.atlassian.net/browse/DBM-1948
When querying child nodes/leafs from tree search, it will now use the parent branch as part of that query so that we only get back the relevant results.
[DBM-1948]: https://invicara.atlassian.net/browse/DBM-1948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DBM-1948: Fix tree search, selected child returning results from other branches

---

packages/ipa-core/src/IpaPageComponents/dashboards/DashboardView.scss

Added responsive design for the Dashboard to avoid overflowing containers

DBM-2169 fix: added responsive design for dashboard

---

packages/ipa-core/src/IpaLayouts/Layout.jsx

https://invicara.atlassian.net/browse/DBM-2292
In a userConfig file add the following setting which is a path to the JSX file relative to /ipaCore folder:
```
{
"settings: {
"sidebarComponent:": "newSidebar/Sidebar"
}
}
```

DBM-2292: Ability to replace default sidebar navigation with custom component

---

packages/ipa-core/package-lock.json
packages/ipa-core/package.json
packages/ipa-core/src/IpaPageComponents/entities/EntityCollectionModal.jsx

Added optional chaining to context object to avoid error.

DBM-2298 Collections modal not opening 

---

packages/ipa-core/package-lock.json
packages/ipa-core/package.json

Releasing a new version of Ipa-core that implements the latest bug fixes.

Pre release/ipa core/3.0.29

---

packages/ipa-core/package-lock.json
packages/ipa-core/package.json

Updating ipa-core version to include the latest changes as per @jonw-ivcr request.

Pre release/ipa core/3.0.31

---

packages/ipa-core/package-lock.json
packages/ipa-core/package.json

Releasing new ipa-core package (v3.0.34) after merge with v2.3

Pre release/ipa core/3.0.34

---

packages/ipa-core/package-lock.json
packages/ipa-core/src/IpaPageComponents/DownloadsView.jsx
packages/ipa-core/src/react-ifef/styles/_styles.scss

https://invicara.atlassian.net/browse/AA-1568

AA-1568: DownloadsView: Loading spinner can be shown until the page loads

---

packages/ipa-core/package-lock.json
packages/ipa-core/package.json

Brining in the latest changes to AA-1568.

Upgrading ipa-core to v3.0.35

---

packages/ipa-core/src/IpaPageComponents/DownloadsView.jsx
packages/ipa-core/src/IpaPageComponents/DownloadsView.scss
packages/ipa-core/src/IpaPageComponents/users/InviteCard.jsx
packages/ipa-core/src/IpaPageComponents/users/UserGroupView.scss

https://invicara.atlassian.net/browse/AA-1107

AA-1107: Small UI changes on Downloads and User Groups pages

---

packages/ipa-core/src/IpaControls/ScriptedChart.jsx

Resolved the Scripted Chart title not appearing on the screen.

DBM-2330 Resolved chart title not appearing on screen

---

packages/ipa-core/package-lock.json
packages/ipa-core/package.json

new release for ipa-core package 3.0.40

new release for ipa-core package 3.0.40

---

packages/ipa-core/src/IpaControls/CreatableScriptedSelects.jsx
packages/ipa-core/src/IpaControls/EnhancedScriptedLinkedSelects.jsx
packages/ipa-core/src/IpaPageComponents/files/FilesTable.jsx
packages/ipa-core/src/IpaPageComponents/files/LinkedSelectValues.js
packages/ipa-core/src/IpaPageComponents/files/UploadFilesWizard.jsx
packages/ipa-core/src/IpaPageComponents/files/UploadFilesWizard.scss
packages/ipa-core/src/IpaPageComponents/files/UploadWizardSteps.jsx
packages/ipa-core/src/IpaPageComponents/files/configReader.jsx

Due to various issue arising from bulk file uploads, I have refactored some of the File Table and Select components. More information can be found here:
https://invicara.atlassian.net/wiki/spaces/~62f0d03a48e310e67297077b/pages/4199448584/FileTable+refactor

DBM-2183 File Table refactor

---

packages/ipa-core/package-lock.json
packages/ipa-core/src/IpaPageComponents/files/ChooseFiles.jsx
packages/ipa-core/src/IpaPageComponents/files/UploadFilesWizard.jsx

Resolving the issue of being able to upload multiple copies of the same file at the same time.

DBM-1517 fix: removing ability to upload multiple copies of the same file at once

---

packages/ipa-core/package.json
packages/ipa-core/src/IpaUtils/ScriptHelper.js
packages/ipa-core/src/IpaUtils/helpers.jsx

https://invicara.atlassian.net/browse/DBM-2371

DBM-2371: Navigator: Export and Relate options are not working
